name: Sbt Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository so that sbt can find your build files.
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Scala and sbt.
      - name: Setup Scala
        uses: olafurpg/setup-scala@v14

      # Run the sbt test command to execute your Scala tests.
      - name: Run sbt tests
        run: sbt test