name: Scala CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository so the workflow can access it
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up a JDK; sbt requires Java.
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      # Cache Ivy and sbt directories to speed up build times
      - name: Cache Ivy, sbt and Coursier directories
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.coursier
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-

      # Run the sbt test command to execute your Scala tests
      - name: Run sbt tests
        run: sbt test

